version: '3.4'

services:
  compose-test:
    image: ${DOCKER_REGISTRY-}composetest
    build:
      context: .
      dockerfile: compose-test/Dockerfile
  composetestweb:
    image: ${DOCKER_REGISTRY-}composetestweb
    build:
      context: .
      dockerfile: test-ui/Dockerfile
  composetest-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Epam_2010"
    volumes:
      - ./data:/var/opt/mssql/data